### ISSUE TITLE
`asset.package` is deprecated. Please use `await asset.getPackage()` instead.

### ISSUE THREAD

**Issue by BenzLeung** [DeMoorJasper/parcel-plugin-imagemin#10]
![image](https://user-images.githubusercontent.com/2764768/41464277-502c8112-70cc-11e8-8e14-870a1e62f331.png)

https://github.com/DeMoorJasper/parcel-plugin-imagemin/blob/12ecc864ccad6348c728ccedb7f4c06e50b01335/lib/assets/ImageAsset.js#L15-L17

I just updated `parcel-bundler` to ver 1.9.0. And I got the warning.

Looks like this warning appears on line 16 of `ImageAsset.js`: `this.package.imagemin`.

**Comment by DeMoorJasper** [comment]
Thanks for reminding me I'll push an update :)

**Comment by DeMoorJasper** [comment]
Fixed in 1.1.2
