### ISSUE TITLE
Not optimizing the images

### ISSUE THREAD

**Issue by victormoretti** [DeMoorJasper/parcel-plugin-imagemin#11]
I am not sure if I configured it right.
After testing with a normal jpg image, it outputs the exact same image despite the configuration.
Normally installed th pack with npm; Inserted the img tag with it's url inside index.html; created the imagemin.config.js file with the readme example. However, no results.
I am missing something or this can actually be an issue?

**Comment by DeMoorJasper** [comment]
It doesn't do anything in dev mode (watch/serve) you can always set the quality lower but it should be low enough to notice it already

**Comment by victormoretti** [comment]
It worked! I was used to gulp-imagemin that optimize during dev mode and thought it would do the same. I suggest to also address this clarification on the readme file. Thanks for the plugin!

**Comment by DeMoorJasper** [comment]
Awesome! I'll add a note to the readme, glad I could help :)
