### ISSUE TITLE
Asset size of minified images are reported in build stats as 0 B during build

### ISSUE THREAD

**Issue by adamduren** [DeMoorJasper/parcel-plugin-imagemin#13]
Files are successfully minified but file size is incorrectly reported.

Side note but unrelated: It would be great to see the "savings" from compression.

![image](https://user-images.githubusercontent.com/581097/44006974-c6dc3c86-9e52-11e8-9a9a-70f9021002f4.png)

**Comment by DeMoorJasper** [comment]
Savings would unfortunately be impossible, but size should be easy to fix

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Implemented in cfbe419fec6bc48ed6ea25a17c01e504ab77c8bc gonna push an incremental release (1.1.3) in a bit

**Comment by adamduren** [comment]
@DeMoorJasper Great work! Thank you.
