### ISSUE TITLE
Additional configuration options

### ISSUE THREAD

**Issue by bre7** [DeMoorJasper/parcel-plugin-imagemin#14]
# 🙋 feature request

`imagemin.config.js` currently supports only the quality param:

```js
module.exports = {
  "quality": 50
};
```

## 🤔 Expected Behavior

Since the plugin uses gifsicle, mozjpeg, etc. to minify the images, then it should provide an api to configure them.

## 😯 Current Behavior

Only quality can be configured.

## 💁 Possible Solution

Allow other options to be specified, for each minifier.

## 🔦 Context

It's impossible to disable SVGs viewbox stripping (there was an issue in parcel's repo) or enabling interlacing/progressive options in GIFs/JPEGs

## 💻 Examples

```js
module.exports = {
  "gifsicle": { "optimizationLevel": 1, "interlaced": true },
  "mozjpeg": { "progressive": true, "quality": 50 },
  "pngquant": { "quality": 50 },
  "svgo": [
    { "removeViewBox": true },
    { "cleanupIDs": false }
  ]
};
```

I'll try and submit a PR asap.

**Comment by DeMoorJasper** [comment]
Thank you, released as v2

**Comment by bre7** [comment]
🎉 Great, you even added the missing tests 👍
