### ISSUE TITLE
Issues with non-asset images

### ISSUE THREAD

**Issue by bre7** [DeMoorJasper/parcel-plugin-imagemin#18]
Hi Jasper, while creating an issue in Parcel's repo I bumped into an issue with the plugin. Using a simple [index.html](https://github.com/bre7/parcel-plugin-imagemin-18/blob/master/dev/index.html) with 2 images: <img> while the other is an href (am I the only one displaying fullscreen images and using Parcel ? 😢).

Is this because the plugin assumes that images will be hashed ? But since one is an entrypoint, it will be copied as-is.

Error message:

> Server running at http://localhost:1234
×  ENOENT: no such file or directory, open 'C:\path\parcel-plugin-imagemin-18\dist\images\gallery\foo.jpeg'
Error: ENOENT: no such file or directory, open 'C:\path\parcel-plugin-imagemin-18\dist\images\gallery\foo.jpeg'

Repro: https://github.com/bre7/parcel-plugin-imagemin-18

**Comment by DeMoorJasper** [comment]
Ow it's probably because my custom packager doesn't check if the directory exists. Should be an easy fix, it assumed the original flat structure parcel originally used.

**Comment by bre7** [comment]
Not sure why but mkdirp isn't working as expected. Managed to fix it with fs-extra, PR asap.
