### ISSUE TITLE
Missing libpng16.so.16

### ISSUE THREAD

**Issue by nextlogic-ono** [DeMoorJasper/parcel-plugin-imagemin#2]
I just ran the example and it showed an error at the jpeg file,
(executed : ./node_modules/.bin/parcel build example/index.html)

🚨 Error in file: parcel-plugin-imagemin/example/pexels-image.jpeg

Command failed: parcel-plugin-imagemin/example/node_modules/mozjpeg/vendor/cjpeg -quality 50
parcel-plugin-imagemin/example/node_modules/mozjpeg/vendor/cjpeg: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory

**Comment by DeMoorJasper** [comment]
Ow this is unexpected, thought i fixed all those issues i'll look into it

**Comment by DeMoorJasper** [comment]
I can't seem to reproduce, this is the command i used, inside the current master branch
`./node_modules/.bin/parcel build example/index.html --no-cache`

**Comment by nextlogic-ono** [comment]
Sorry this could be related to #3.

**Comment by nextlogic-ono** [comment]
After installing required packages to compile mozjpeg in #3, additionally installing 'libpng16-dev' package fixed it and now the example bundles with no errors.

I guess it's mozjpeg's problem for not being able to provide a working binary via npm and builds a non static binary when it compiles, even though the command line says "--disable-shared".

**Comment by strarsis** [comment]
@windware: Your fix worked great for me in WSL, too.
