### ISSUE TITLE
Animated webp support

### ISSUE THREAD

**Issue by SnO2WMaN** [DeMoorJasper/parcel-plugin-imagemin#23]
(I know this issue shouldn't be posted in this repository, however [imagemin-webp](https://github.com/imagemin/imagemin-webp) seemed to be no longer develping. )

Animated webp will be supported?

![code_2018-09-02_03-12-56](https://user-images.githubusercontent.com/15155608/44948748-26728b80-ae5e-11e8-9f76-b03dd2cea62a.png)

**Comment by DeMoorJasper** [comment]
I have no clue what webp is, that's why I originally didn't support it. @bre7 was so nice to contribute it into the repo, perhaps he has any idea if it would be possible and how to do it.

**Comment by bre7** [comment]
Mmmh not sure. I thought imagemin’s webp was active. Jasper's plugin is just a wrapper for parcel, and relies on imagemin for minifying. 

Closing as this is an issue with imagemin-webp and not parcel's plugin.
