### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by FDiskas** [DeMoorJasper/parcel-plugin-imagemin#25]
`
warning parcel-plugin-imagemin > imagemin-gifsicle > gifsicle > bin-wrapper > download > gulp-decompress > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
`

**Comment by DeMoorJasper** [comment]
This is unrelated to this plugin as it’s just a deprecation of a dependency of a dependency of a dependency...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
