### ISSUE TITLE
Getting build error after installing

### ISSUE THREAD

**Issue by boonier** [DeMoorJasper/parcel-plugin-imagemin#26]
```$ parcel index.htmlServer running at http://localhost:1234
⚠️  Unexpected identifier  async addAsset(asset) {
        ^^^^^^^^
SyntaxError: Unexpected identifier
    at NativeCompileCache._moduleCompile (/GIT-work/The-Student-Rooms/enlitened-client-app/node_modules/v8-compile-cache/v8-compi
le-cache.js:226:18)    at Module._compile (/GIT-work/The-Student-Rooms/enlitened-client-app/node_modules/v8-compile-cache/v8-compile-cache.js:172:36
)    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
🚨  /GIT-work/The-Student-Rooms/enlitened-client-app/src/components/PageHeader/PageHeader.css:undefined:undefined: Unexpected iden
tifier
  async packageImage(options, location) {
        ^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at NativeCompileCache._moduleCompile (/GIT-work/The-Student-Rooms/enlitened-client-app/node_modules/v8-compile-cache/v8-compi
le-cache.js:226:18)
    at Module._compile (/GIT-work/The-Student-Rooms/enlitened-client-app/node_modules/v8-compile-cache/v8-compile-cache.js:172:36
)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)    at require (/GIT-work/The-Student-Rooms/enlitened-client-app/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Parser.findParser (/GIT-work/The-Student-Rooms/enlitened-client-app/node_modules/parcel-bundler/lib/Parser.js:77:45)
    at Parser.getAsset (/GIT-work/The-Student-Rooms/enlitened-client-app/node_modules/parcel-bundler/lib/Parser.js:84:22)
```

I had to remove the plugin for the time being as it was preventing normal builds.

cheers

**Comment by DeMoorJasper** [comment]
Seems like you are using node 6 or 7 this plugin only supports node 8 or higher.

**Comment by boonier** [comment]
Ahh good spot. Thanks I'll give it a go.

**Comment by boonier** [comment]
Hi

OK so I'm on node v10.8.0 and I reinstalled the plugin. Builds fine.

Now I'm getting the error in console:

`enlitened-client-app.e31bb0bc.js:39 Uncaught (in promise) Error: Cannot find module 'src/components/User/temp_user.jpg'`

where I'm doing `import user from './temp_user.jpg';`

Uninstalling the plugin it imports fine

cheers

**Comment by boonier** [comment]
did you mean to close this @DeMoorJasper?

**Comment by DeMoorJasper** [comment]
Isn't it resolved?

**Comment by boonier** [comment]
Sorry no, I probably wasn't clear :)

So after upgrading to node 10.8.0 the parcel build errors went away, but then another problem occurred, when trying to get the URL of an image via import.

The only way to continue was to remove the plugin.

N.B. This is in normal development mode, not when building. Also the error is in the browser.

**Comment by DeMoorJasper** [comment]
Not sure why this is happening, this plugin doesn't change any of the naming or import related things. It just minified and saves the image.

Maybe clear your cache? Not sure if that would help, it might though as node version is not part of the cache key afaik. But there is probably not a cache record as it threw an error before

**Comment by boonier** [comment]
I have postcss-parcel-import and postcss-easy-import in my postcss config.

Could either of these be conflicting? (I wanted to just put it out there before breaking and isolating things in my app)

**Comment by DeMoorJasper** [comment]
@boonier don't think it has anything to do with it, haven't used any postCSS plugins for importing.

Not ruling it out entirely though, feel free to debug it.

**Comment by boonier** [comment]
@DeMoorJasper it appears that this plugin is still getting in on the action when NODE_ENV is in development. Should that be happening?

**Comment by DeMoorJasper** [comment]
Depends on what you mean with get in on the action.

It does not do any minifications if that's what you're saying

**Comment by boonier** [comment]
What I meant was should the images be passing through the plugin in development mode in the first place.

I did a little bit of debugging - time is a bit limited right now - but it appears to running through all the images imported into the app component tree,  importing them fine it would seem, then passing them through `ImagePackager` into a Buffer, then result of which is not digestible by the browser.

**Comment by boonier** [comment]
I should clarify that any build command is minifying fine, just development is causing problems.

**Comment by DeMoorJasper** [comment]
Alright I'll try something and comment with a PR shortly

**Comment by DeMoorJasper** [comment]
Idk man, tried to improve the tests and add some stuff in the hope to reproduce any of the issues in this issue. But once again have failed to reproduce this. https://github.com/DeMoorJasper/parcel-plugin-imagemin/pull/27

**Comment by boonier** [comment]
Umm that is odd. Points to something in my setup I suspect, maybe one of the other parcel import plugins I'm using.

When I get some downtime I'll do a stripped back app and try to isolate the problem, and get back to this issue (I can reopen if necessary). I can live without this functionality for the time being.

Cheers

**Comment by FDiskas** [comment]
`sudo apt-get install libpng-dev` fixed for me build issues
