### ISSUE TITLE
Image buffer is undefined

### ISSUE THREAD

**Issue by fr3fou** [DeMoorJasper/parcel-plugin-imagemin#28]
After installing the dev dependency, and trying to build for production, I get this error:

![image](https://user-images.githubusercontent.com/1344906/51226661-15cc3900-1959-11e9-9994-50e38087ae72.png)

**Comment by DeMoorJasper** [comment]
Could u provide any reproducable repo?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fr3fou** [comment]
[Sure](https://github.com/fr3fou/fr3fou.github.io)

**Comment by fr3fou** [comment]
Just note that I removed the dependency as I needed to build my site. Add it again and report if it occurs on your machine too.

**Comment by DeMoorJasper** [comment]
Builds just fine for me.

**Comment by fr3fou** [comment]
I'm using parcel with it installed globally, could this be the issue?

**Comment by fr3fou** [comment]
Tried it with the local dependency, same results

**Comment by DeMoorJasper** [comment]
@fr3fou not sure what's cauing this. Could you give some info about the OS and Node version you're running. Perhaps try to debug this a little yourself if you can. Might be an imagemin bug

**Comment by fr3fou** [comment]
```sh
simo@lust:~
> hostnamectl   
   Static hostname: lust
         Icon name: computer-laptop
           Chassis: laptop
  Operating System: Antergos Linux
            Kernel: Linux 4.20.1-arch1-1-ARCH
      Architecture: x86-64
```

```sh
simo@lust:~
> node --version
v8.15.0
```

```sh
simo@lust:~
> yarn --version
1.13.0
```

```sh
simo@lust:~
> parcel --version                             
1.11.0
```

**Comment by fr3fou** [comment]
I ended up making a Dockerfile and building it inside a container which worked lmao, still sorta pissed why it didn't work :c

**Comment by DeMoorJasper** [comment]
Well not sure what to do about this, it seems to simply have no content set. Meaning the result of imagemin is either null or something weird happened inside parcel.

The only things I can think of anymore is cache if it's a Parcel issue. Strange that it won't log an error if it's a imagemin issue though

**Comment by remborg** [comment]
Hi, I had a similar error message when running the parcel dev server:
```
🚨  Image buffer is undefined for ../assets/logo.png
at ImagePackager.addAsset (/home/remi/Projects/UXEN/website/node_modules/parcel-plugin-imagemin/lib/ImagePackager.js:14:13)
    at Bundle._addDeps (/home/remi/Projects/UXEN/website/node_modules/parcel-bundler/src/Bundle.js:227:20)
    at Bundle._package (/home/remi/Projects/UXEN/website/node_modules/parcel-bundler/src/Bundle.js:196:18)
    at <anonymous>
```
But it was building fine.

Changing the path of my assets folder from parent folder ../ to the src folder ./ fixed it for me.
