### ISSUE TITLE
Adding plugin causes glob import to break

### ISSUE THREAD

**Issue by butlersrepos** [DeMoorJasper/parcel-plugin-imagemin#29]
Using a glob import for my png files ala, `import PICS from './*.png';` works fine without the plugin.

However, adding the plugin causes **dev mode** to display the following issue
![image](https://user-images.githubusercontent.com/1380635/52549569-b65f1e80-2d88-11e9-839d-e4cae868cffd.png)

**Comment by butlersrepos** [comment]
https://github.com/butlersrepos/parcel-imagemin-issue

example repo, yarn install and run dev to see

**Comment by DeMoorJasper** [comment]
Not sure what's causing this. It seems to generate the output just fine.

EDIT: Kinda fixed it, gonna cleanup some code and open a PR so ya can have a look. I'll push a release tomorrow
