### ISSUE TITLE
mozjpeg install fails

### ISSUE THREAD

**Issue by nextlogic-ono** [DeMoorJasper/parcel-plugin-imagemin#3]
Running 'npm i' in the current master branch tells me that mozjpeg binary fails to run properly and goes onto compile it and initially it stopped saying 'autoreconf' was not found and I just installed autoconf but it stops here. This is perhaps mozjpeg's problem.

> > mozjpeg@5.0.0 postinstall parcel-plugin-imagemin/node_modules/mozjpeg
> > node lib/install.js
> 
>   ⚠ The `parcel-plugin-imagemin/node_modules/mozjpeg/vendor/cjpeg` binary doesn't seem to work correctly
>   ⚠ mozjpeg pre-build test failed
>   ℹ compiling from source
>   ✖ Error: autoreconf -fiv && ./configure --disable-shared --disable-dependency-tracking --with-jpeg8  --prefix="parcel-plugin-imagemin/node_modules/mozjpeg/vendor" --bindir="parcel-plugin-imagemin/node_modules/mozjpeg/vendor" --libdir="parcel-plugin-imagemin/node_modules/mozjpeg/vendor" && make -j1 && make install -j1
> Command failed: autoreconf -fiv
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force 
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: not using Libtool
> autoreconf: running: /usr/bin/autoconf --force
> configure.ac:23: error: possibly undefined macro: AC_PROG_LIBTOOL
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> autoreconf: /usr/bin/autoconf failed with exit status: 1
>
>    at ChildProcess.exithandler (child_process.js:275:12)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at maybeClose (internal/child_process.js:925:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.5.1
| Node             | 8.9.4
| npm         | 5.6.0
| Operating System | Ubuntu 16.04.3

**Comment by nextlogic-ono** [comment]
It compiled after installing,
> autoconf libtool pkg-config nasm

**Comment by nextlogic-ono** [comment]
imagemin-mozjpeg has the issue reported.
https://github.com/imagemin/imagemin-mozjpeg/issues/26

**Comment by DeMoorJasper** [comment]
Thanks for reporting this i'll re-open this for anyone that might encounter the same issue, untill the issue inside imagemin-mozjpeg is fixed

**Comment by mkg20001** [comment]
Seems fixed https://github.com/imagemin/imagemin-mozjpeg/issues/26#issuecomment-443803869
