### ISSUE TITLE
Adds a .js file for each image

### ISSUE THREAD

**Issue by leifniem** [DeMoorJasper/parcel-plugin-imagemin#31]
I don't know if this is intended, but when adding the plugin i get a .js file for each image that is processed. Those files end up linked in the `<head>` of my HTML files, causing a lot of clutter.

For most images the `src` is set correctly, however images linked in the `head` like the OpenGraph image get completely replaced by the resulting script.

I'm not sure if this is related to #29, but it seems possible to me.

Examples of the output:

![image](https://user-images.githubusercontent.com/5417518/56851428-8ba84f00-690f-11e9-9b33-6dc9d865a5dd.png)

![image](https://user-images.githubusercontent.com/5417518/56851478-0ec9a500-6910-11e9-8b9e-24dfb3dba61e.png)

**Comment by DeMoorJasper** [comment]
This is to fix the glob bug we had a little while ago.

Unfortunately I'm not sure how to fix this as all images now output a JS fragment. (I could remove this behaviour but that would break globs)

**Comment by leifniem** [comment]
I see. Is it necessary for the scripts to remain in the HTML for the images to work when building the project? As far as i can tell the images are linked correctly, so the scripts add execution and load time to the final output, which is my main concern.

**Comment by DeMoorJasper** [comment]
The js files don’t need to be loaded. Only globs need them and parcel should handle that out of the box and make it part of whatever bundle they’re required in. 

So no they don’t need to be in your html

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leifniem** [comment]
okay. Since the plugin currently adds them when running the build command i think that is the essence of this issue then.

**Comment by DeMoorJasper** [comment]
Like I said I can't fix it without breaking globs. Will be fixed with Parcel 2 though

**Comment by leifniem** [comment]
Sorry, misunderstood that. Thank you for your work, i'll try it with Parcel 2 once it's out :)
