### ISSUE TITLE
Default quality level without imagemin.config.js?

### ISSUE THREAD

**Issue by nextlogic-ono** [DeMoorJasper/parcel-plugin-imagemin#4]
Is it possible to set it to 100 by changing,
>      let quality = config.quality || 100;
to
>      let quality = config && config.quality || 100;
?

**Comment by DeMoorJasper** [comment]
Ow sure i’ll change it

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
Should be fixed in latest version, also did a performance and mainly stability improvement by not always including every plugin
