### ISSUE TITLE
Take advantage of caching

### ISSUE THREAD

**Issue by lbguilherme** [DeMoorJasper/parcel-plugin-imagemin#5]
Only assets seems to be cached. As the minification here happens on the packager, it is always processed again, even when the source didn't change.

**Comment by DeMoorJasper** [comment]
I'll look into improving this

**Comment by DeMoorJasper** [comment]
Should be done in https://github.com/DeMoorJasper/parcel-plugin-imagemin/commit/bfeaccaa40574f1e48e03866ad120d201c5f39d8
