### ISSUE TITLE
Images get larger and don't load in dev mode, works fine on build

### ISSUE THREAD

**Issue by tobinbradley** [DeMoorJasper/parcel-plugin-imagemin#6]
I saw this behavior on my project but to make sure I wasn't crazy I cloned this repo and tried the example folder. 

`yarn run clean-build` completes with no errors. `yarn start` makes images in the dist folder that are larger than the original (ex: parcel.png went from 204kb to 356kb) and they don't appear to be images. They are binary, but they won't load in the browser or for image preview on the desktop. No errors, just bad image files.

`yarn run build` and the images are minified and load fine. 

I can't see a different path in your code based on dev vs build, so I don't know what to suggest. I'd say it's a personal problem with my GCC compiled image handlers (I'm on Arch linux) but since the build step produces good images...beats me.

Thanks in advance for any suggestions you could provide!

**Comment by DeMoorJasper** [comment]
Ow this is weird i’ll look into this, normally this code just forwards the buffer to output if it’s not building. Probably a bug with loading the image data

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
