### ISSUE TITLE
Parcel v2 / Transformer version

### ISSUE THREAD

**Issue by mkg20001** [DeMoorJasper/parcel-plugin-imagemin#61]
Is there a transformer based version planned for the parcel v2 release?

**Comment by DeMoorJasper** [comment]
Yes, I think this would be an optimised plugin but wanna wait until parcel 2 reaches a more stable version. Probably alpha 3 or something

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ihornechypor** [comment]
and what about plugin that converts images to webP? It will be only in v2 or also in v1 ?

**Comment by DeMoorJasper** [comment]
I'm no longer adding new features to this plugin, the parcel 2 imageminification plugin will be part of the parcel 2 monorepo https://github.com/parcel-bundler/parcel/pull/4209
