### ISSUE TITLE
Plugin generate js files

### ISSUE THREAD

**Issue by duskohu** [DeMoorJasper/parcel-plugin-imagemin#63]
Hi, I use this plugin. I have one problem, plugin generate 2 files, one new image file and second with same filename but js file. I have zero configuration.
Example:
`bg.23124bf0.png, bg.23124bf0.js`

**Comment by DeMoorJasper** [comment]
Yeah this is a bug and a fix. It's a weird fix to get glob imports to work.

Kind of wanna undo the change, I might do it in the next release.

**Comment by Ihornechypor** [comment]
Hi, any news ? When will be new release?

**Comment by Ihornechypor** [comment]
i've found from where it  comes in ImageAsset.js  this 3 lines of code
`
    {
        type: 'js',
        value: `module.exports=${JSON.stringify(pathToAsset)};`,
        hasDependencies: false
      },
`

**Comment by DeMoorJasper** [comment]
@Ihornechypor I know how to fix it, it was a regression. If I undo it, the glob bug will return.

Anyway I'll push a new release with the fix, it'll be a major release though...

**Comment by Ihornechypor** [comment]
@DeMoorJasper thanks :)
