### ISSUE TITLE
JPG images are being saved as [object Object]

### ISSUE THREAD

**Issue by lbguilherme** [DeMoorJasper/parcel-plugin-imagemin#7]
![screenshot from 2018-01-30 21-38-36](https://user-images.githubusercontent.com/546954/35599143-191d1d5c-0606-11e8-8469-7f3cb1d306a2.png)

This happens for the released 1.0.1 version

**Comment by DeMoorJasper** [comment]
Thanks for reporting this issue, should be fixed in 1.0.2

**Comment by lbguilherme** [comment]
Thanks!
