### ISSUE TITLE
Can we specify "imagemin"."quality" in package.json?

### ISSUE THREAD

**Issue by suazithustra** [DeMoorJasper/parcel-plugin-imagemin#8]
Will this work?
i.e. in `package.json`
```
"imagemin": {
  "quality": 50
}
```

**Comment by DeMoorJasper** [comment]
No this won't work, it shouldn't be hard to add, feel free to make a pr. Let me know if you're not intrested in implementing this, than i'll try add this feature in the near future

**Comment by suazithustra** [comment]
Will do.
