### ISSUE TITLE
option: skip-if-larger

### ISSUE THREAD

**Issue by Ihornechypor** [DeMoorJasper/parcel-plugin-imagemin#84]
Hi, if it possible add option skip-if-larger to imagemin.config.js?? 
Sometimes after optimisation images are bigger then were before :(

**Comment by DeMoorJasper** [comment]
Seems weird that it happens, could you create a reproduction repo for this?

I could also compare buffer sizes but than that should be the default. Compressing to a larger size seems pretty ridiculous and useless.

**Comment by Ihornechypor** [comment]
@DeMoorJasper  issue with compare buffer sizes sounds great. Unfortunately this issue happens only at our project, because some of our images have already optimised, and pngquant make them bigger :)
pngquant has option --skip-if-larger but  it only works on cli mode.

**Comment by DeMoorJasper** [comment]
@Ihornechypor ow that makes sense, I'll implement this and make it the default non configurable option as imo nobody wants an optimiser to make their files larger

**Comment by Ihornechypor** [comment]
@DeMoorJasper great thanks for your fast reply :)

**Comment by DeMoorJasper** [comment]
@Ihornechypor could you validate this is fixed, published as `4.0.1-beta`?

**Comment by Ihornechypor** [comment]
@DeMoorJasper tested, and works for me :) now images with smaller size save their size, and quality.

**Comment by DeMoorJasper** [comment]
@Ihornechypor awesome, will push a non beta release
