### ISSUE TITLE
The picture will appear undefined

### ISSUE THREAD

**Issue by QAQLiuCong** [DeMoorJasper/parcel-plugin-imagemin#9]
The picture will appear undefined, I use parcel in the VsCode and then install the plug-in, the picture in the dist, open the display undefined, or directly open the display picture error.

{
  "name": "vueproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "parcel index.html",
    "build": "parcel build index.html --no-source-maps --public-url ."
  },
  "alias": {
    "vue": "./node_modules/vue/dist/vue.common.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "vue": "^2.5.16",
    "vue-hot-reload-api": "^2.3.0"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^1.3.1",
    "autoprefixer": "^8.6.1",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-vue": "^2.0.2",
    "cssnano": "^3.10.0",
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.8.1",
    "parcel-plugin-imagemin": "^1.1.1",
    "postcss-modules": "^1.1.0",
    "precss": "^3.1.2",
    "vue-template-compiler": "^2.5.16"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8",
    "iOS >= 7",
    "Android > 4.1"
  ]
}

node:v10.2.0
npm:6.1.0
os:win10

**Comment by DeMoorJasper** [comment]
Could you set-up a reproduction repository, so I can test this?

**Comment by QAQLiuCong** [comment]
Sorry, I'm using Google Translate. Sorry, it's weird that there is no problem now. It was OK to re-install the reliance on the win7 computer at home yesterday. It is also possible to try a computer today, but there is a small question to ask. If I build, the picture size is from 6.68kb to 2.11kb, but change the quality, no matter how much, the picture is still 2.11kb? Parcel display Picture is 0b, actual 2.11kb.

Dist\main.b672f127.js   190.54 KB   607.91s
Dist\index.html   290 B   1.61s
Dist\main.74747d1f.css   228 B   14.89s
Dist\logo.d9e078ab.png   0 B   6.01s

This is the test https://github.com/QAQLiuCong/parcel-vue-demo
