### ISSUE TITLE
Doesn't work with glob requires?

### ISSUE THREAD

**Issue by ghost** [DeMoorJasper/parcel-plugin-imagemin#90]
I load all my png images like this,
```js
const images = require('../assets/images/projects/**/*.png');
```
and it works. So I wanted to compress them also and I added `parcel-plugin-imagemin` and now I get this error in the console and nothing seems to load,
```
Unhandled Promise Rejection: Error: Cannot find module 'assets/images/projects/Numberz/app1.png'
```
It seems the plugin doesn't respect relative paths I think.

Directory structure is here: https://github.com/pyros2097/website/tree/master/assets/images/projects

parcel-bundler: "^1.12.4"

**Comment by DeMoorJasper** [comment]
This is a known issue, it has been fixed before but I undid the change as it would emit a JS file for each image, there's probably a better way to fix it and maybe should even be fixed within Parcel core but Parcel 1 is in maintenance mode.

Related fix: 0f94a7485b5b462bdfba1120ab0688604b330ab6

You could use an old version of this plugin `3.0.0`

**Comment by ghost** [comment]
Thanks. Will try the old version and see if it works. And find an alternative to compress the png assests.

**Comment by DeMoorJasper** [comment]
Why do you need an alternative? The old version should just work fine and compress your png assets

**Comment by ghost** [comment]
Ohh yeah I thought the old version might fail with the current parcel version. It worked. Thanks.
