### ISSUE TITLE
minimize images from static folder

### ISSUE THREAD

**Issue by spooky** [DeMoorJasper/parcel-plugin-imagemin#92]
I'm using parcel with parcel-plugin-static-files-copy and store a set of images in the static dir that are loaded dynamically.
Looks like the parcel-plugin-imagemin does not pick these up. Is there a way to specify an extra source directory?

**Comment by DeMoorJasper** [comment]
Currently that’s not possible and I'm not really planning to add extra features to this plugin at the moment
