### ISSUE TITLE
Wrong destination for .gif files on parcel build

### ISSUE THREAD

**Issue by yoanmalie** [DeMoorJasper/parcel-plugin-imagemin#93]
Hi,
When running `parcel build` only my `.gif` files goes to the `/dist` folder instead `/dist/img/` like all others images (jpeg, png, svg…) that I tested.

I created a repo for the issue with of all my config: https://github.com/yoanmalie/imagemin-parcel-bug

**Step:**
- Add files to `/src/img/` and call them in the `index.html`:
`<img src="./img/file-name.gif">`.
- Run  `npm run build`

**Versions:**
macOS 10.14.6
node 10.17.0
npm 6.12.0
parcel 1.12.4

**Comment by DeMoorJasper** [comment]
naming is not part of this plugin, that's part of parcel core. I think it's because it's not in the exclusion list of special files.
