### ISSUE TITLE
Plugin causes Error on production build: "Cannot find module 'ihem'"

### ISSUE THREAD

**Issue by skoshx** [DeMoorJasper/parcel-plugin-imagemin#95]
Hello, I tried using this plugin, but when i pushed to production, and navigated off the main page (eg. to /pages), and refreshed the page, I got this error.

Uncaught (in promise) Error: Cannot find module 'ihem'

I have absolutely NO idea how to fix it since it doesn't show where the error stems from.

**Comment by joshbedo** [comment]
yeah this project looks broken

**Comment by DeMoorJasper** [comment]
I have no clue why this happens can't reproduce it. Updated dependencies, maybe this fixes it.

There's tests for this project that pass... so feel free to fix this instead of being negative and profiteering from voluntary open source maintainers @joshbedo
