### ISSUE TITLE
Threw the following error: Error: Cannot find module 'parcel-bundler\src\utils\config'

### ISSUE THREAD

**Issue by AltusJVR** [DeMoorJasper/parcel-plugin-imagemin#97]
Screenshot of the error:

![parcel-imagemin-error-2](https://user-images.githubusercontent.com/69439444/110889769-879c3500-82cd-11eb-96e2-961406496f0a.JPG)

Folder Structure: 

![parcel-imagemin-error](https://user-images.githubusercontent.com/69439444/110889786-91be3380-82cd-11eb-937a-fc021f105127.JPG)

Config file: 
![parcel-imagemin-error-3](https://user-images.githubusercontent.com/69439444/110889926-d4800b80-82cd-11eb-8c7c-050902306420.JPG)

**Comment by stalker3343** [comment]
Same error

**Comment by DeMoorJasper** [comment]
whats the content of your package.json?

**Comment by AltusJVR** [comment]
I have moved to Parcel-V2. I have tried to find something in my initial commits, but it seems I removed the repo where I used Parcel-V1.
